### ISSUE TITLE
Create a branch that uses latest A-Frame build's raycaster component

### ISSUE THREAD

**Issue by ngokevin** [mayognaise/aframe-mouse-cursor-component#1]
https://github.com/aframevr/aframe/blob/master/src/components/raycaster.js

**Comment by mayognaise** [comment]
@ngokevin hey so how shall i use the component? adding `raycaster` as attribute in `a-scene` then call `this.el.components.raycaster.raycaster` from `mouse-cursor` component?

**Comment by theDrGray** [comment]
Any update on this?

**Comment by mayognaise** [comment]
hi @theDrGray sorry for the late response.
i'll check this when i have time...

**Comment by Disorrder** [comment]
well, raycaster properties are very useful. F.e. you can fire events with specified css selector

**Comment by graywithanA** [comment]
@theDrGray @Disorrder I've [forked](https://github.com/graywithanA/aframe-mouse-cursor-component) this project and added support for the `objects` property.  I've also got a PR with those changes in to this repo.   After seeing @ngokevin's request to implement the raycaster component, I may take a crack at that in the near future

**Comment by mayognaise** [comment]
Hi @graywithanA thank you for the PR. let me update it now..
However since there are many PRs I didn't update, I'll add them one by one..
Sorry for leaving it for a while :(

**Comment by ArnaudRemi** [comment]
Hello.

Is the feature still waiting for integration?
I wasn't able to find it into the sources.

Many thanks for your work :)

**Comment by mayognaise** [comment]
This feature is now available in A-Frame v0.6.1 by setting `<a-scene cursor="rayOrigin: mouse">`. 😄
