### ISSUE TITLE
AFRAME.utils.device is undefined

### ISSUE THREAD

**Issue by sebi-b** [mayognaise/aframe-mouse-cursor-component#11]
Hey there,

I get the following error, when loading your script:

TypeError: AFRAME.utils.device is undefined[Weitere Informationen]  aframe-mouse-cursor-component.min.js:1:403
	<anonym> https://rawgit.com/mayognaise/aframe-mouse-cursor-component/master/dist/aframe-mouse-cursor-component.min.js:1:403
	t https://rawgit.com/mayognaise/aframe-mouse-cursor-component/master/dist/aframe-mouse-cursor-component.min.js:1:102
	<anonym> https://rawgit.com/mayognaise/aframe-mouse-cursor-component/master/dist/aframe-mouse-cursor-component.min.js:1:194
	<anonym> https://rawgit.com/mayognaise/aframe-mouse-cursor-component/master/dist/aframe-mouse-cursor-component.min.js:1:2

I use the latest a-frame.min.js. Any help?
Thank you,

sebi

**Comment by mayognaise** [comment]
hi before the file, did you add actual `aframe.js`?

**Comment by sebi-b** [comment]
Hi,

Indeed, I had a wrong version of a-frame, thank you very much!
