### ISSUE TITLE
Option to hold on an object to trigger something?

### ISSUE THREAD

**Issue by sebi-b** [mayognaise/aframe-mouse-cursor-component#14]
Hey there!

Is it possible to hold the mousebutton over an object for some seconds to trigger an animation?

For example I have a cube and I want the cube to rotate if the user clicks and holds the cube for 3 seconds.

Thanks!

**Comment by mayognaise** [comment]
This feature is now available in A-Frame v0.6.1 by setting `<a-scene cursor="rayOrigin: mouse">`. 😄
