### ISSUE TITLE
Does not react with gLTF models

### ISSUE THREAD

**Issue by brendanluu** [mayognaise/aframe-mouse-cursor-component#22]
Appears to only be working with .obj files. gLTF support would be awesome! Would you consider adding it?

**Comment by sachinaglave** [comment]
I made it working by replacing line no: 499 with 

`var intersects = __raycaster.intersectObjects([scene], true);`

**Comment by sachinaaglave** [comment]
By replacing line no: 499 with `var intersects = _raycaster.intersectObjects([scene], true);
` it should work

**Comment by mauriciomartinez-itesm** [comment]
You can use this:

AFRAME.registerComponent('raycaster-autorefresh', {
  init: function () {
    var el = this.el;
    this.el.addEventListener('model-loaded', function () {
      var cursorEl = el.querySelector('[raycaster]');
      cursorEl.components.raycaster.refreshObjects();
    });
  }
});

for every model you add to the scene...

**Comment by mayognaise** [comment]
This feature is now available in A-Frame v0.6.1 by setting `<a-scene cursor="rayOrigin: mouse">`. 😄
