### ISSUE TITLE
Initialization correct after moving scene on desktop

### ISSUE THREAD

**Issue by michaelvogt** [mayognaise/aframe-mouse-cursor-component#27]
When opening an aframe scene in a desktop browser, it seems like the initialization of the mouse cursor component is only done after moving the scene with the mouse. Before doing so, it seems the mouse reaction is inverted, not reacting when clicking the object with an event, but anywhere else.

You can have a look at 
https://vrarr.glitch.me/basic.html

**Comment by mayognaise** [comment]
This feature is available in A-Frame since v0.6.1 by setting `<a-scene cursor="rayOrigin: mouse">`. 😄
