### ISSUE TITLE
Question about Click? 

### ISSUE THREAD

**Issue by stevel4857** [mayognaise/aframe-mouse-cursor-component#28]
I would like to change camera position on click using this. Is this possible? 

My code based on your code.

    <a-scene cursor="rayOrigin: mouse">
      <a-box position="0 3.5 -2" rotation="30 30 0" color="skyblue"
             event-set__enter="_event: mouseenter; material.color: yellowgreen; scale: 3 1 1"
             event-set__leave="_event: mouseleave; material.color: skyblue; scale: 1 1 1"
	         event-set__click=" _target: #mycamera; animation: to: 0 0 100;">

I have the event set component loaded in. Does that work with this? 

This was the original event set code for teleport that did work:

event-set__1="_event: click; _target: #mycamera; position: 0 2 4;"

Thanks for any help.

**Comment by stevel4857** [comment]
I guess this makes more sense even though it doesn't work.

    <a-scene cursor="rayOrigin: mouse">
      <a-box position="0 3.5 -2" rotation="30 30 0" color="skyblue"
             event-set__enter="_event: mouseenter; material.color: yellowgreen; scale: 3 1 1"
             event-set__leave="_event: mouseleave; material.color: skyblue; scale: 1 1 1"
	         event-set__click="_target: #mycamera; position: 0 2 4;">
      </a-box>

**Comment by stevel4857** [comment]
Solution:

    <a-scene cursor="rayOrigin: mouse">
      <a-box position="0 3.5 -2" rotation="30 30 0" color="skyblue"
             event-set__enter="_event: mouseenter; material.color: yellowgreen; scale: 3 1 1"
             event-set__leave="_event: mouseleave; material.color: skyblue; scale: 1 1 1;"
	         event-set__click="_event: click; _target: #mycamera; position: 0 2 4;">
      </a-box>

**Comment by mayognaise** [comment]
This feature is available in A-Frame since v0.6.1 by setting `<a-scene cursor="rayOrigin: mouse">`. 😄
