### ISSUE TITLE
No longer works in A-Frame 0.7

### ISSUE THREAD

**Issue by UXVirtual** [mayognaise/aframe-mouse-cursor-component#29]
I've just tried upgrading one of my demo scenes to A-Frame 0.7, and looks like the mouse cursor component no longer registers clicks on the scene. See demo:

https://hazardu5.github.io/aframe-workshop/examples/09/finish/

I'm using clickable hotspot made from `<a-circle>` that are supposed to trigger an informational dialog box.

It broke somewhere between commit `adabe788bb1a6f015a939f8fb84dd86365ce4565` and 0.7 release of A-Frame.

It's worth noting that https://github.com/tizzle/aframe-orbit-controls-component is also affected.

**Comment by UXVirtual** [comment]
Looks like it might be related to some other event listeners that are inside the scene. I'll investigate further.

**Comment by UXVirtual** [comment]
Nope, definitely not working. It may be related to how the binding of `mousedown`, `mouseup`, `click` etc happens in `_attachEventListeners()`. There were some changes to how the canvas is applied to the scene so that may be interfering with something here.

**Comment by UXVirtual** [comment]
I have a fix for this now. PR incoming.

**Comment by UXVirtual** [comment]
Pull request is now available here: #30

**Comment by AndreaMonzini** [comment]
Hello, i have the same problem.
Could you please provide the "aframe-mouse-cursor-component.min.js" updated version compatible with A-Frame 0.7? 
Thank you.

**Comment by dsinni** [comment]
+1, as well as in A-Frame `0.8.*`.

This is a very useful component and would be great if it was compatible with the latest versions.

Keep up the great work.

Thanks.

**Comment by ngokevin** [comment]
This feature has been part of the A-Frame core since v0.6.x.

https://github.com/mayognaise/aframe-mouse-cursor-component#a-frame-mouse-cursor-component

`<a-entity cursor="rayOrigin: mouse">`
