### ISSUE TITLE
Not working with aframe-ui-modal-component

### ISSUE THREAD

**Issue by iKoala** [mayognaise/aframe-mouse-cursor-component#3]
Thanks for making this component, it saved me lots of time to work with the mouse click event.

I am trying to use mouse-cursor component with [aframe-ui-modal-component](https://github.com/IdeaSpaceVR/aframe-ui-modal-component), however, the mouse click event doesn't work when the entities are wrapped inside the ui-modal, any hints about this problem?

(Other entities are working as intended with mouse-cursor when they are not wrapped inside the ui-modal.)

**Comment by mayognaise** [comment]
Hi @iKoala sorry for the late response.
I haven't supported ui-model-component yet.
will do when I have time...
Thank you!
