### ISSUE TITLE
an update for 0.8 ?

### ISSUE THREAD

**Issue by arthurmougin** [mayognaise/aframe-mouse-cursor-component#33]
Aframe 0.8.2
Oculus browser and Safari IOS
with touch event, the click work randomly..
Is there a way to fix it ?

**Comment by Jason-LI-M** [comment]
Change init function 

> 
		init: function init() {
			this._raycaster = new THREE.Raycaster();
			this._mouse = new THREE.Vector2();
			this._isMobile = this.el.sceneEl.isMobile;
			this._isStereo = false;
			this._active = false;
			this._isDown = false;
			this._intersectedEl = null;
			this._attachEventListeners();
			// this._canvasSize = false;
			// /* bind functions */
			// this.__getCanvasPos = this._getCanvasPos.bind(this);
			// this.__getCanvasPos = this._getCanvasPos.bind(this);
			// this.__onEnterVR = this._onEnterVR.bind(this);
			// this.__onExitVR = this._onExitVR.bind(this);
			// this.__onDown = this._onDown.bind(this);
			// this.__onClick = this._onClick.bind(this);
			// this.__onMouseMove = this._onMouseMove.bind(this);
			// this.__onRelease = this._onRelease.bind(this);
			// this.__onTouchMove = this._onTouchMove.bind(this);
			// this.__onComponentChanged = this._onComponentChanged.bind(this);
		},
Move the 'bind' to `_attachEventListeners()` function

> _attachEventListeners: function() {
			var el = this.el;
			var sceneEl = el.sceneEl;
			var canvas = sceneEl.canvas;
			if (!canvas) {
				el.sceneEl.addEventListener('render-target-loaded', this._attachEventListeners.bind(this));
				return;
			}
            this._canvasSize = false;
			window.addEventListener('resize', this._getCanvasPos.bind(this));
			document.addEventListener('scroll', this._getCanvasPos.bind(this));
			this._getCanvasPos();
			sceneEl.addEventListener('enter-vr', this._onEnterVR.bind(this));
			sceneEl.addEventListener('exit-vr', this._onExitVR.bind(this));
			canvas.addEventListener('mousedown', this._onDown.bind(this));
			canvas.addEventListener('mousemove', this._onMouseMove.bind(this));
			canvas.addEventListener('mouseup', this._onRelease.bind(this));
			canvas.addEventListener('mouseout', this._onRelease.bind(this));
			canvas.addEventListener('touchstart', this._onDown.bind(this));
			canvas.addEventListener('touchmove', this._onTouchMove.bind(this));
			canvas.addEventListener('touchend', this._onRelease.bind(this));
			canvas.addEventListener('click', this._onClick.bind(this));
            el.addEventListener('componentchanged', this._onComponentChanged.bind(this));
		},

ps: first time answer question on github

**Comment by nathanhannig** [comment]
A-Frame has this functionality built in now, try adding this to a cursor entity.
cursor="rayOrigin: mouse".

**Comment by mayognaise** [comment]
This feature is now available in A-Frame v0.6.1 by setting `<a-scene cursor="rayOrigin: mouse">`. 😄
