### ISSUE TITLE
Update GitHub description to say it's deprecated and now a core feature in A-Frame.

### ISSUE THREAD

**Issue by ngokevin** [mayognaise/aframe-mouse-cursor-component#35]

**Comment by PlumCantaloupe** [comment]
I can't seem to find it in Aframe. Where should we be looking?

**Comment by PlumCantaloupe** [comment]
Okay just found the PR : https://github.com/aframevr/aframe/pull/2861

**Comment by nathanhannig** [comment]
I agree, this needs to be updated to make users aware.

I stumbled across this component from StackOverflow and did not know it existed in A-Frame.

A-Frame has this functionality built in now, try adding this to a cursor entity.
cursor="rayOrigin: mouse".

**Comment by ngokevin** [comment]
Hey @mayognaise, can you update the GitHub description to note this component is now built into A-Frame? Many developers are still missing the message.

**Comment by mayoyml** [comment]
@ngokevin ah im so sorry. will update the version.

**Comment by mayognaise** [comment]
@ngokevin Ah I'm sorry. Will update it soon.

**Comment by ngokevin** [comment]
Thank you!

**Comment by mayognaise** [comment]
@ngokevin added!
https://www.npmjs.com/package/aframe-mouse-cursor-component

![image](https://user-images.githubusercontent.com/588874/54444113-4fbe7f00-46ff-11e9-9ced-529ccbe3d8cd.png)
