### ISSUE TITLE
Does not react to collada models

### ISSUE THREAD

**Issue by Rosefalk** [mayognaise/aframe-mouse-cursor-component#5]
The component doesn't seem to recognize <a-collada-model> and will not fire events off of them

**Comment by mayognaise** [comment]
Hi @Rosefalk, sorry for the late response.
Can the Collada model be recognized with regular cursor event?

**Comment by Rosefalk** [comment]
Yes, normal cursor events were fine. I ended up rolling my own component since this one (in my project) caused massive frame drops in IE when mouse is moved.

**Comment by mayognaise** [comment]
Hi @Rosefalk thank you for response.
I'm happy to hear you figured it out.
I have to debug to make this work with the new version..

**Comment by Rosefalk** [comment]
If you want I can maybe show you what I did for comparison?

**Comment by mayognaise** [comment]
Hi @Rosefalk that would be super awesome!!
I really appreciate your contribution 😄

**Comment by ghost** [comment]
I was wondering if you had a version of your component that worked with collada, I'm using it in a project and it would be incredibly helpful.
