### ISSUE TITLE
Z-Index fighting

### ISSUE THREAD

**Issue by Drewwit** [mayognaise/aframe-mouse-cursor-component#6]
Hello! Thanks for making this component, it is amazing and a great way to shoehorn desktop and mobile navigational elements. I am making a rather large tour, and am finding that even hidden elements will stop the mouse cursor from being able to interact with elements "behind" the hidden ones. While the native Aframe cursor will still work fine. Do you have any guidance or potential solutions?

**Comment by mayognaise** [comment]
hi @Drewwit sorry for the late response.
Ah I see. Thought this works but maybe no longer support with new verison..
I'll check this out when I have time.

**Comment by mayognaise** [comment]
This feature is now available in A-Frame v0.6.1 by setting `<a-scene cursor="rayOrigin: mouse">`. 😄
