### ISSUE TITLE
Mouse cursor component not working when stage is inside a DIV

### ISSUE THREAD

**Issue by Maxisoft2** [mayognaise/aframe-mouse-cursor-component#7]
Hey guys,

When you use AFRAME as a part of a whole HTML page (e.g. a banner) the mouse cursor component refuses to work. It does kind of work, but the positioning of the "hotspots" is off: When I try to click an object, I need to click closely next to it to actually hit it. It's almost like the raycast is not emitted from the tip of my mouse pointer anymore then but somewhere a couple of hundred pixels next to it.

As we really need this to work for a project in January, does anybody have a clue on how to fix this? I have been picking my brains over this one for the last few days....

Best!
 Max

**Comment by Maxisoft2** [comment]
Hey guys,

Just a heads-up: I have found out that the raycast is influenced by how many pixels there are between the start of the A-FRAME scene and the top of the page. So, I suppose the "Y"-Coordinates for the raycast are calculated from the point where the actual page begins, but not from where the Aframe stage begins. Thus, if you add a DIV with aframe that is at the bottom of the page, you have a discrepancy of exactly the amount of pixels that are between the top of the page and the beginning of the stage. I suppose this could be easily fixed?

Best!
- Max

**Comment by mayognaise** [comment]
Hi @Maxisoft2, sorry for the late response.
This mouse cursor is designed only if the canvas is full-browser size.
I'll fix to check the canvas position/size in the future.
Sorry I don't have time right now but please create a PR if you implement this feature.
Thank you!

**Comment by toychicken** [comment]
Hi all, I've done a PR for a fix for this - https://github.com/mayognaise/aframe-mouse-cursor-component/pull/17

**Comment by harrio** [comment]
I'm using mouse cursor on an embedded scene with orbit controls. For some reason the raycaster still often seems to have some kind of an offset quite frequently. I'm unsure whether this has something to do with the orbit controls or just the page offset. 

It almost seems like the cursor works fine if the page has been scrolled at least once. If the objects in the embedded scene fit on the page (but the whole scene doesn't) on page load and the orbit controls are used, then there's an offset and the raycast misses. But if I scroll down the page and back everything works fine from there on.

Anyone with similar problems?

EDIT:
I did a bit of debugging and initially offsetW in the _getPosition function is 0 even though the canvas does not start from the left edge of the page. After scrolling when the scroll listener is triggered the offset is correct. So the mouse position always has an incorrect x offset on initial page load.

The first this._getCanvasPos(); call seems to occur too early.

**Comment by toychicken** [comment]
I've noticed this too. In my project, we've got around it by triggering a
resize event on the `renderstart` event, and that seems to fix. However,
not sure yet why it happens at all.

**Comment by mayognaise** [comment]
This feature is now available in A-Frame v0.6.1 by setting `<a-scene cursor="rayOrigin: mouse">`. 😄
