### ISSUE TITLE
Gaze timeout 

### ISSUE THREAD

**Issue by rahirschi** [mayognaise/aframe-mouse-cursor-component#8]
Hi,
Nice component. Very handy. But it over-rides the timeout command inside cursor. ie timeout="10"

Is there a way to have the timeout work for gaze but this component work as it is?

**Comment by mayognaise** [comment]
@rahirschi hi sorry for the late response.
Ah I see. Let me see what I can do.

**Comment by mayognaise** [comment]
This feature is now available in A-Frame v0.6.1 by setting `<a-scene cursor="rayOrigin: mouse">`. 😄
